/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projetoacademico.view;

import com.projetoacademico.DAO.AlunoDAO;
import com.projetoacademico.model.Aluno;
import javax.swing.JOptionPane;

/**
 *
 * @author TESTE
 */
public class TelaAluno extends javax.swing.JFrame {
    private com.projetoacademico.DAO.AlunoDAO dao = new com.projetoacademico.DAO.AlunoDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAluno.class.getName());

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
        atualizarTabela();
        modoPadrao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMatricula.setText("Matrícula:");

        lblNome.setText("Nome:");

        lblCurso.setText("Curso:");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Curso"
            }
        ));
        jScrollPane1.setViewportView(tblAlunos);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMatricula)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatricula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(35, 35, 35)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurso)
                            .addComponent(btnNovo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnBuscar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
try{
    String input = javax.swing.JOptionPane.showInputDialog(this, "Digite a matrícula que deseja buscar: ");
    if (input == null || input.isEmpty()) {
        return;
    }
    int matricula = Integer.parseInt(input);
    com.projetoacademico.model.Aluno aluno = dao.consultar(matricula);
    
    if (aluno != null) {
        txtMatricula.setText(String.valueOf(aluno.getMatricula()));
        txtNome.setText(aluno.getNome());
        txtCurso.setText(aluno.getCurso());
        modoBusca(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Aluno não encontrado");
        modoPadrao();
    }
} catch (NumberFormatException e){
    javax.swing.JOptionPane.showMessageDialog(this, "Matrícula inválida");
} catch (Exception e){
    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
try {
    if(txtMatricula.getText().isEmpty()){
throw new Exception("O campo Matrícula é obrigatório!");
    }// TODO add your handling code here:
    int matricula = Integer.parseInt(txtMatricula.getText());
    String nome = txtNome.getText();
    String curso = txtCurso.getText();
    com.projetoacademico.model.Aluno aluno = new com.projetoacademico.model.Aluno(matricula, nome, curso);
    if (dao.consultar(matricula) == null) {
        dao.incluir(aluno);
        javax.swing.JOptionPane.showMessageDialog(this, "Aluno Cadastrado com sucesso!");
    } else {
        dao.alterar(aluno);
        javax.swing.JOptionPane.showMessageDialog(this,"Dados do aluno atualizados");
    }
    atualizarTabela();
    modoPadrao();
    
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro: A matrícula deve ser um número inteiro", "Confirmação", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage());
}
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
try{
    int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);

if (resposta == javax.swing.JOptionPane.YES_OPTION) {
int matricula = Integer.parseInt(txtMatricula.getText());
dao.excluir(matricula);
atualizarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Aluno Excluído");
modoPadrao();
}
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir:" + e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
modoEdicao();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
modoPadrao();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
modoEdicao();
txtMatricula.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
private void limparCampos(){
    txtMatricula.setText("");
    txtNome.setText("");
    txtCurso.setText("");
}
private void atualizarTabela(){
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblAlunos.getModel();
    modelo.setNumRows(0);
    
    for (com.projetoacademico.model.Aluno a : dao.listarTodos()) {
        modelo.addRow(new Object[] {
            a.getMatricula(),
            a.getNome(),
            a.getCurso()
        });
    }
}
private void modoPadrao() {
    btnNovo.setEnabled(true);
    btnBuscar.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnAlterar.setEnabled(false);
    btnCancelar.setEnabled(false);
    
    txtMatricula.setEnabled(false);
    txtNome.setEnabled(false);
    txtCurso.setEnabled(false);
    limparCampos();
}
private void modoEdicao() {
    btnNovo.setEnabled(false);
    btnBuscar.setEnabled(false);
    btnSalvar.setEnabled(true);
    btnExcluir.setEnabled(false);
    btnAlterar.setEnabled(false);
    btnCancelar.setEnabled(true);
    
    txtMatricula.setEnabled(true);
    txtNome.setEnabled(true);
    txtCurso.setEnabled(true);
    
    txtMatricula.requestFocus();
}
private void modoBusca(boolean encontrou){
    if (encontrou) {
        btnNovo.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnCancelar.setEnabled(true);
    } else {
        modoPadrao();
    }
}
}
