/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projetoacademico.view;

import com.projetoacademico.DAO.DisciplinaDAO;
import com.projetoacademico.model.Disciplina;
import javax.swing.JOptionPane;
/**
 *
 * @author TESTE
 */
public class TelaDisciplina extends javax.swing.JFrame {
private com.projetoacademico.DAO.DisciplinaDAO dao = new com.projetoacademico.DAO.DisciplinaDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDisciplina.class.getName());

    /**
     * Creates new form TelaDisciplina
     */
    public TelaDisciplina() {
        initComponents();
        atualizarTabela();
        modoPadrao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCargaHoraria = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCargaHoraria = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisciplinas = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodigo.setText("Código:");

        lblNome.setText("Nome:");

        lblCargaHoraria.setText("Carga Horária:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Carga Horária"
            }
        ));
        jScrollPane1.setViewportView(tblDisciplinas);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCargaHoraria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargaHoraria)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnBuscar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
try{ 
    if (txtCodigo.getText().isEmpty() || txtNome.getText().isEmpty() || txtCargaHoraria.getText().isEmpty()) {
throw new Exception("Preencha todos os campos!");
    }
String codigo = txtCodigo.getText();
String nome = txtNome.getText();

int carga = Integer.parseInt(txtCargaHoraria.getText());

com.projetoacademico.model.Disciplina d = new com.projetoacademico.model.Disciplina(codigo, nome, carga);
if (dao.consultar(codigo) == null) {
dao.incluir(d);
javax.swing.JOptionPane.showMessageDialog(this,"Salvo com Sucesso");
} else {
dao.alterar(d);
javax.swing.JOptionPane.showMessageDialog(this, "Alterado com sucesso");
}

atualizarTabela();
modoPadrao();
txtCodigo.setText(""); txtNome.setText(""); txtCargaHoraria.setText("");
} catch (NumberFormatException e) {
javax.swing.JOptionPane.showMessageDialog(this, "A Carga Horária deve ser um número");
} catch (Exception e) {
javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
try{
    String codigoBusca = javax.swing.JOptionPane.showInputDialog(this, "Digite o código da disciplina: ");
if (codigoBusca == null || codigoBusca.isEmpty()) {
    return;
}
com.projetoacademico.model.Disciplina d = dao.consultar(codigoBusca);

if (d != null) {
txtNome.setText(d.getNome());
txtCargaHoraria.setText(String.valueOf(d.getCargaHoraria()));
txtCodigo.setText(d.getCodigo());
modoBusca();
} else {
javax.swing.JOptionPane.showMessageDialog(this, "Disciplina não encontrada");
modoPadrao();
}
} catch (Exception e) {
javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
try {
    String codigo = txtCodigo.getText();
int confirma = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir?", "Tem certeza?", javax.swing.JOptionPane.YES_NO_OPTION);

if (confirma == javax.swing.JOptionPane.YES_OPTION) {
dao.excluir(codigo);
atualizarTabela();
javax.swing.JOptionPane.showMessageDialog(this, "Excluído");
modoPadrao();
}
} catch (Exception e) {
javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
modoPadrao();
        txtCodigo.setText("");
txtNome.setText("");
txtCargaHoraria.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
modoEdicao();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
modoEdicao();
txtCodigo.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDisciplina().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargaHoraria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblDisciplinas;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
private void atualizarTabela() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblDisciplinas.getModel();
    modelo.setNumRows(0);
    
    for (com.projetoacademico.model.Disciplina d : dao.listarTodos()) {
        modelo.addRow(new Object[] {
            d.getCodigo(),
            d.getNome(),
            d.getCargaHoraria()
        });
    }
}
private void modoPadrao() {
    btnNovo.setEnabled(true);
    btnBuscar.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnCancelar.setEnabled(false);
    
    txtCodigo.setEnabled(false);
    txtNome.setEnabled(false);
    txtCargaHoraria.setEnabled(false);
    
    txtCodigo.setText("");
    txtNome.setText("");
    txtCargaHoraria.setText("");
}
private void modoEdicao() {
    btnNovo.setEnabled(false);
    btnBuscar.setEnabled(false);
    btnSalvar.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
    
    txtCodigo.setEnabled(true);
    txtNome.setEnabled(true);
    txtCargaHoraria.setEnabled(true);
    
    txtCodigo.requestFocus();
}
private void modoBusca(){
    btnNovo.setEnabled(false);
    btnBuscar.setEnabled(false);
    btnSalvar.setEnabled(false);
    btnAlterar.setEnabled(true);
    btnExcluir.setEnabled(true);
    btnCancelar.setEnabled(true);
}
}
